title: "Dev Prakash Srivastava"
name: "Dev Prakash Srivastava"
email: "dev.sriv99@gmail.com"
description: "M.Sc. Economics and Social Sciences — Bocconi University | Aspiring Economics PhD Student"
baseurl:
url: "https://devpra1999.github.io"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
author:
  name: "Dev Prakash Srivastava"
  avatar: "/assets/images/headshot.jpg" 
  bio: "M.Sc. Economics and Social Sciences at Bocconi University | Aspiring Economics PhD Student"
  location: "Italy"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:dev.sriv99@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/devpra"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/devpra1999"

# Defaults for page layouts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
